### ISSUE TITLE
request_interceptor error when i'm uncomment

### ISSUE THREAD

**Issue by hanafiahtkj** [KevinZhang19870314/flutter_getx_boilerplate#3]
**request_interceptor.dart**

==============

import 'dart:async';

import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:get/get_connect/http/src/request/request.dart';
import 'package:flutter_getx_boilerplate/shared/shared.dart';

FutureOr<Request> requestInterceptor(request) async {
  final token = StorageService.box.pull(StorageItems.accessToken);

  request.headers['X-Requested-With'] = 'XMLHttpRequest';
  request.headers['Authorization'] = 'Bearer $token';

  EasyLoading.show(status: 'loading...');
  return request;
}

**storage_service.dart**
=====================

import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';

class StorageService extends GetxService {
  Future<SharedPreferences> init() async {
    return await SharedPreferences.getInstance();
  }
}

can you help me please

**Comment by xaverine** [comment]
I'd like to thank KevinZhang19870314 for providing this starter template.
I'm a Flutter newbie and this has helped me to jump start my own project!

To hanafiahtkj,

try replacing the following
`
final token = StorageService.box.pull(StorageItems.accessToken);
`

with actual SharedPreferences setter & getter, please refer to package's info
[https://pub.dev/packages/shared_preferences](url)
