### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by hanafiahtkj** [KevinZhang19870314/flutter_getx_boilerplate#4]
i have been custom your code

response_interceptor.dart
======================

void handleErrorStatus(Response response) {
  switch (response.statusCode) {
    case 400:
      final message = ErrorResponse.fromJson(response.body);
      CommonWidget.toast(message.message);
      break;
    case 403:
      final message = ErrorResponse.fromJson(response.body);
      print(message.message);
      //CommonWidget.toast(message.message);
      Get.toNamed(Routes.VERIFY_EMAIL);
      break;
    default:
  }

==============================
api_repository.dart
======================

Future<UserResponse?> getUser() async {
    final res = await apiProvider.getUser('/api/user');
    if (res.statusCode == 200) {
      return UserResponse.fromJson(res.body);
    }
  }

when iam run, i am get this error, in file api_repository.dart

Exception has occurred.
_CastError (type 'Null' is not a subtype of type 'Response<dynamic>' in type cast)

**Comment by xaverine** [comment]
exception might be coming from 

`fromJson(res.body)`

put a break point on res.body to see its content

I personally use the bodyString instead...

`Response.fromRawJson(res.bodyString.toString())`
